import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f7fa',
        padding: 16,
        paddingTop: 10,
        justifyContent: 'space-between',
        marginTop: 55,
    },
    headerSection: {
        marginTop: 5,
        marginBottom: 25,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
        marginBottom: 10,
        marginLeft: 5,
    },
    deviceCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    deviceHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    deviceInfo: {
        flex: 1,
    },
    deviceName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#023457',
        marginBottom: 4,
    },
    deviceSubtitle: {
        fontSize: 14,
        color: '#666',
    },
    statusContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 4, // Consistent margin for top and bottom
    },
    statusIndicator: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginRight: 6,
    },
    statusConnected: {
        backgroundColor: '#4CAF50',
    },
    statusDisconnected: {
        backgroundColor: '#F44336',
    },
    statusText: {
        fontSize: 13,
        color: '#555',
    },
    watchIcon: {
        width: 55,
        height: 65,
        marginRight: 12,
    },
    buttonsContainer: {
        marginTop: 10,
    },
    buttonsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    connectButton: {
        backgroundColor: '#023457',
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        width: '48%',
        height: 50,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    connectButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    generateReportButton: {
        backgroundColor: '#fff',
        borderColor: '#023457',
        borderWidth: 1.5,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        width: '48%',
        height: 50,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    disconnectButtonText: {
        color: '#023457',
        fontSize: 16,
        fontWeight: 'bold',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.6)',
    },
    modalContent: {
        width: '90%',
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#023457',
        marginBottom: 16,
        textAlign: 'center',
    },
    calendar: {
        borderRadius: 12,
        marginBottom: 20,
        borderWidth: 1,
        width: 300,
        borderColor: '#e0e0e0',
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    button: {
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 20,
        elevation: 2,
        marginHorizontal: 5,
        flex: 1,
    },
    buttonClose: {
        backgroundColor: '#9e9e9e',
    },
    buttonConfirm: {
        backgroundColor: '#023457',
    },
    textStyle: {
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
        fontSize: 16,
    },
    loadingContent: {
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 24,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 5,
        minWidth: 220,
    },
    loadingText: {
        marginTop: 14,
        fontSize: 16,
        fontWeight: '500',
        color: '#023457',
    },
});
